// <auto-generated />
using System;
using Ejercicio3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio3.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    [Migration("20230905231419_create-database")]
    partial class createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ejercicio3.IngresoVehiculo", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEgreso");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaIngreso");

                    b.Property<int>("LugarAsignado")
                        .HasColumnType("int")
                        .HasColumnName("LugarAsignado");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Patente");

                    b.HasKey("id");

                    b.ToTable("Ingresos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
